### ISSUE TITLE
missing license for the repo

### ISSUE THREAD

**Issue by chenrui333** [a1dutch/sonarqube-bash-completion#1]
👋 Just found this repo does not have any license, it would be good to add OSI-approved one, https://spdx.org/licenses/

Some popular license choice would be:
- MIT
- Apache-2.0
- BSD-3-Clause

**Comment by a1dutch** [comment]
@chenrui333 i have added apache license, thanks for reporting

**Comment by chenrui333** [comment]
Thanks @a1dutch!
